events {
    worker_connections 1024;
}

http {
    upstream ml-backend {
        server ml-service-v1:5000 weight=9 max_fails=2 fail_timeout=30s;
        server ml-service-v2:5000 weight=1 max_fails=2 fail_timeout=30s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ml-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        }

        location /v1/ {
            proxy_pass http://ml-service-v1:5000/;
        }

        location /v2/ {
            proxy_pass http://ml-service-v2:5000/;
        }
    }
}
